using EventsBookingBackend.Infrastructure.Notification.Telegram.Entities;
using EventsBookingBackend.Infrastructure.Persistence.Configurations.Base;

namespace EventsBookingBackend.Infrastructure.Persistence.Configurations.Telegram;

public class TelegramUserConfiguration : BaseEntityConfiguration<TelegramUser>;