name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          PAYME_LOGIN: ${{ PAYME_LOGIN }}
          PAYME_PASSWORD: ${{ PAYME_PASSWORD }}
        run: |
          # Save the SSH private key to a temporary file
          echo "$VPS_SSH_KEY" > vps_key.pem
          chmod 600 vps_key.pem
          
          ssh -i vps_key.pem -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP 'echo "PAYME_LOGIN=$PAYME_LOGIN" >> /tmp/env_vars.txt'  # Add additional variables as needed
          ssh -i vps_key.pem -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP 'echo "PAYME_PASSWORD=$PAYME_PASSWORD" >> /tmp/env_vars.txt'  # Add additional variables as needed

          # Run the deployment script on the remote VPS
          ssh -i vps_key.pem -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP 'source /tmp/env_vars.txt && bash -s' < ./deploy.sh
          
          # Remove the key file after use
          rm vps_key.pem
          ssh -i vps_key.pem -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP 'rm /tmp/env_vars.txt'